export const PAGECODES = {
    LANDING:'MobileVerify',
    ADDITIONAL_INFORMATION:'AdditionalInformation',
    PRODUCT_DESCRIPTION:'MobileVerify',
    MORE_INFO:'MobileVerify',
    LOAN_SUMMARY:'MobileVerify',
    PREVIEW_PAGE:'MobileVerify',



    MOBILE_VERIFY: "MobileVerify",
    MORE_INFO: "MoreInfo",
    STATUS_CHECK: "StatusCheck",
    PERSONAL_DETAILS: "PersonalDetails",
    EMPLOYMENT_DETAILS: "EmploymentDetails",
    DOCUMENT_UPLOAD_V2: "DocumentUpload",
    SANCTION_DETAILS: "SanctionDetails",
    KEY_FACT_DETAILS: "KeyFactDetails",
    LOAN_SUMMARY: "LoanSummary",
    CONTACT_BRANCH: "ContactBranch",
    ESIGN: "ESign",
    EMAIL_VERIFY: 'EmailVerify',
    PAN_VERIFY: 'PanVerify',
    EKYC_VERIFY: 'EKycVerify',
    PRODUCT_SELECTION: 'ProductSelection',
    AADHAR_VERIFY: 'AadharVerify',
    PRODUCT_ERROR: 'ProductError',
    CUSTOMER_TYPE: 'CustomerType',

    ADDRESS_DETAILS: 'AddressDetails',

    PREVIEW_PAGE: 'PreviewPage',
    CONTRACTS: 'Contracts',
    UDYAM_VERIFY: 'UdyamVerify',
    ACCOUNT_VERIFY: 'AccountVerify',
    KCC_LAND: 'KCCLand',
    KCC_CROP: 'KCCCrop',
    DOCUMENT_LIST: 'DocumentList',
    DECLARATION: 'Declaration',
    DOCUMENTATION_COMPLETE: 'DocumentComplete',
    VEHICLE_DETAILS: 'VehicleDetails',
    BRANCH_DETAILS: 'BranchDetails',
   // ADDITIONAL_INFORMATION: 'AdditionalInformation',
    JOURNEY_PREVIEW: 'JourneyPreview',
    TRACK_APPLICATION: 'TrackApplication',
    VKYC: 'VideoKYC',
    VKYC_Processing: 'VideoKYCProcessing',
}
